# Generated by Django 5.2.3 on 2025-06-24 03:02

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Title')),
                ('jira_id', models.CharField(db_index=True, max_length=100, verbose_name='Jira Id')),
                ('objective', models.TextField(verbose_name='Objective')),
                ('current_status', models.CharField(db_index=True, max_length=50, verbose_name='Current Status')),
                ('steps_taken', models.TextField(verbose_name='Steps Taken')),
                ('relevant_links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('next_steps', models.TextField(verbose_name='Next steps')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-id'],
            },
        ),
    ]
