services:
 db:
    image: postgres:17
    container_name: weekly-status-db-container
    environment:
        POSTGRES_DB: ${DATABASE_NAME}
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    env_file:
        - .env
 
 django-web:
    build: .
    container_name: weekly-status-django-container
    ports:
        - "8000:8000"
    depends_on:
        - db
    volumes:
     - .:/app

 ollama:
    image: ollama/ollama
    container_name: weekly-status-llm
    ports:
        - "11434:11434"
    volumes:
        - ./entrypoint.sh:/entrypoint.sh:ro
        - ollama:/root/.ollama
    entrypoint: sh -c "sh /entrypoint.sh"

volumes:
    postgres_data:
    ollama: